### ISSUE TITLE
RangeError thrown from toStringAsFixed

### ISSUE THREAD

**Issue by kibantony** [a14n/dart-decimal#14]
Dart VM version: 2.0.0-dev.43.0.flutter-52afcba357 (Fri Mar 30 20:33:12 2018 +0000) on "macos_x64"

The following code:
```
    Decimal d = Decimal.parse('21.19999694824219');
    d.toStringAsFixed(1);
```
Throws the following exception:
```
When the exception was thrown, this was the stack:
#0      Uint32List.[]= (dart:typed_data/runtime/libtyped_data_patch.dart:2465:7)
#1      _BigIntImpl._divRem (dart:core/runtime/libbigint_patch.dart:1382:19)
#2      _BigIntImpl._rem (dart:core/runtime/libbigint_patch.dart:1306:5)
#3      _BigIntImpl.% (dart:core/runtime/libbigint_patch.dart:1697:18)
#4      _gcd (package:rational/rational.dart:34:11)
#5      new Rational (package:rational/rational.dart:87:17)
#6      Rational.* (package:rational/rational.dart:146:46)
#7      Rational.round (package:rational/rational.dart:210:25)
#8      Rational.toStringAsFixed (package:rational/rational.dart:356:28)
#9      Decimal.toStringAsFixed (package:decimal/decimal.dart:218:17)
```

Since the exception originates in BigInt, I filed a similar issue here:
https://github.com/dart-lang/sdk/issues/32898

**Comment by kibantony** [comment]
Ah, I see now you filed https://github.com/dart-lang/sdk/issues/32739
Looks like this might be fixed?

**Comment by a14n** [comment]
Yes it should be fixed in a upcoming dart roll.
