### ISSUE TITLE
Index out of range: index must not be negative: -1

### ISSUE THREAD

**Issue by modulovalue** [a14n/dart-decimal#33]
Do you know why that happens, looks like a bug with BigInt? I'll provide an example of a concrete Rational as soon as I have one.
```
(index): Index out of range: index must not be negative: -1 #0      Uint32List.[] (dart:typed_data-patch/typed_data_patch.dart:2493:7)
#1      _BigIntImpl.toDouble (dart:core-patch/bigint_patch.dart:2413:24)
#2      _BigIntImpl./ (dart:core-patch/bigint_patch.dart:1696:43)
#3      Rational.toDouble (package:rational/rational.dart:261:34)
#4      Decimal.toDouble (package:decimal/decimal.dart:170:34)
```

Edit: filed https://github.com/dart-lang/sdk/issues/41819

**Comment by a14n** [comment]
Agree, it looks related to Dart SDK. It would be awesome to know which Decimal string causes this issue.

**Comment by modulovalue** [comment]
```dart
void main() {
  final a = BigInt.parse("-3696164633313280000000000000");
  final b = BigInt.parse("3481750906500548125063");
  print("${a / b}"); // RangeError (index): Index out of range: index must not be negative: -1
}
```

**Comment by modulovalue** [comment]
Closing this, as it will be fixed by the issue linked above.
